'use strict';

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const tar = require('tar');

const ROOT = path.join(__dirname, '..', '..');

function resolveNpmCli(env) {
  const configured = [env.AEXOS_PARITY_NPM_CLI, env.npm_execpath].filter(Boolean);
  const pathDirs = (env.PATH || env.Path || '').split(path.delimiter).filter(Boolean);
  const candidates = [
    ...configured,
    ...configured.map((candidate) => path.join(path.dirname(candidate), 'npm-cli.js')),
    ...pathDirs.flatMap((binDir) => [
      path.join(binDir, 'node_modules', 'npm', 'bin', 'npm-cli.js'),
      path.resolve(binDir, '..', 'lib', 'node_modules', 'npm', 'bin', 'npm-cli.js'),
    ]),
  ];
  return candidates.find((candidate) => fs.existsSync(candidate));
}

function runNpm(args, options) {
  const npmCli = resolveNpmCli(options.env || process.env);
  if (npmCli) {
    return execFileSync(process.execPath, [npmCli, ...args], options);
  }

  const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  return execFileSync(npmCommand, args, {
    ...options,
    shell: process.platform === 'win32',
  });
}

describe('npm package generated-file boundary', () => {
  test('real npm pack excludes lifecycle output and preserves hook sources and configuration', async () => {
    const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'aexos-pack-policy-'));

    try {
      const rootPackage = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
      const packageExclusions = rootPackage.files.filter((entry) => entry.startsWith('!'));
      fs.writeFileSync(
        path.join(fixture, 'package.json'),
        JSON.stringify({
          name: 'aexos-pack-policy-test',
          version: '1.0.0',
          files: ['.aexos-core/', '.claude/hooks/', ...packageExclusions],
          scripts: { prepack: 'node generate-pack-contaminants.js' },
        }),
      );

      const files = {
        '.aexos-core/data/entity-registry.yaml': 'entities: []\n',
        '.claude/hooks/hook.py': 'print("source retained")\n',
        '.claude/hooks/hook.pyd': 'native extension retained',
        '.claude/hooks/wrapper.cjs': 'module.exports = {};\n',
        '.claude/hooks/config.json': '{"enabled":true}\n',
      };

      for (const [relativePath, content] of Object.entries(files)) {
        const absolutePath = path.join(fixture, relativePath);
        fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
        fs.writeFileSync(absolutePath, content);
      }

      fs.writeFileSync(
        path.join(fixture, 'generate-pack-contaminants.js'),
        [
          "const fs = require('fs');",
          "fs.mkdirSync('.aexos-core/data', { recursive: true });",
          "fs.mkdirSync('.claude/hooks/__pycache__', { recursive: true });",
          "fs.writeFileSync('.aexos-core/data/registry-update-log.jsonl', '{\"generated\":true}\\n');",
          "fs.writeFileSync('.claude/hooks/__pycache__/hook.cpython-313.pyc', 'generated cache');",
          "fs.writeFileSync('.claude/hooks/hook.pyc', 'generated bytecode');",
          "fs.writeFileSync('.claude/hooks/hook.pyo', 'optimized bytecode');",
        ].join('\n'),
      );

      const artifactDir = path.join(fixture, 'artifacts');
      const extractDir = path.join(fixture, 'extracted');
      fs.mkdirSync(artifactDir);
      fs.mkdirSync(extractDir);
      const npmEnvironment = {
        ...process.env,
        npm_config_cache: path.join(fixture, '.npm-cache'),
      };
      const output = runNpm(['pack', '--json', '--pack-destination', artifactDir], {
        cwd: fixture,
        encoding: 'utf8',
        env: npmEnvironment,
        stdio: ['ignore', 'pipe', 'pipe'],
      });
      const packed = JSON.parse(output)[0];
      const packedFiles = packed.files.map((entry) => entry.path);
      await tar.x({ file: path.join(artifactDir, packed.filename), cwd: extractDir });

      expect(packedFiles).toEqual(
        expect.arrayContaining([
          '.aexos-core/data/entity-registry.yaml',
          '.claude/hooks/hook.py',
          '.claude/hooks/hook.pyd',
          '.claude/hooks/wrapper.cjs',
          '.claude/hooks/config.json',
        ]),
      );
      expect(packedFiles).not.toContain('.aexos-core/data/registry-update-log.jsonl');
      expect(packedFiles.some((file) => file.includes('/__pycache__/'))).toBe(false);
      expect(packedFiles.some((file) => /\.(?:pyc|pyo)$/i.test(file))).toBe(false);
      expect(fs.existsSync(path.join(fixture, '.aexos-core/data/registry-update-log.jsonl'))).toBe(
        true,
      );
      expect(fs.existsSync(path.join(fixture, '.claude/hooks/__pycache__/hook.cpython-313.pyc'))).toBe(
        true,
      );
      expect(fs.existsSync(path.join(fixture, '.claude/hooks/hook.pyc'))).toBe(true);
      expect(fs.existsSync(path.join(fixture, '.claude/hooks/hook.pyo'))).toBe(true);
      for (const excluded of [
        '.aexos-core/data/registry-update-log.jsonl',
        '.claude/hooks/__pycache__/hook.cpython-313.pyc',
        '.claude/hooks/hook.pyc',
        '.claude/hooks/hook.pyo',
      ]) {
        expect(fs.existsSync(path.join(extractDir, 'package', excluded))).toBe(false);
      }

      for (const retained of [
        '.aexos-core/data/entity-registry.yaml',
        '.claude/hooks/hook.py',
        '.claude/hooks/hook.pyd',
        '.claude/hooks/wrapper.cjs',
        '.claude/hooks/config.json',
      ]) {
        expect(fs.readFileSync(path.join(extractDir, 'package', retained))).toEqual(
          fs.readFileSync(path.join(fixture, retained)),
        );
      }
    } finally {
      fs.rmSync(fixture, { recursive: true, force: true });
    }
  });

  test('npm command fallback works without npm_execpath', () => {
    const env = { ...process.env };
    delete env.npm_execpath;
    delete env.AEXOS_PARITY_NPM_CLI;
    const version = runNpm(['--version'], {
      encoding: 'utf8',
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    expect(version.trim()).toMatch(/^\d+\.\d+\.\d+$/);
  });
});
